## Numeric Data Type in Pandas

In [1]:
import pandas as pd

In [3]:
#creating a Dataframe with integer data
data={
    'Age':[25,30,26,28,20],
    'salary':[2334,1434,13434,3434,2343]}
df=pd.DataFrame(data)
df

   Age  salary
0   25    2334
1   30    1434
2   26   13434
3   28    3434
4   20    2343

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     5 non-null      int64
 1   salary  5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes

In [6]:
df.dtypes

Age       int64
salary    int64
dtype: object

In [8]:
df['Age']=df['Age'].astype('int32')
df['salary']=df['salary'].astype('int32')
df.dtypes

Age       int32
salary    int32
dtype: object

## Object datatype

In [14]:
# Create a dictionary with mixed data types
data={'Name':['Rr','Mm','Aa','Ss'],
      'Age':[25,23,24,26],
      'Occupation' :['Data Sci','Software','Teacher','engineer'],
      'Salary':[2344,34653,23453,56234]}
data

{'Name': ['Rr', 'Mm', 'Aa', 'Ss'],
 'Age': [25, 23, 24, 26],
 'Occupation': ['Data Sci', 'Software', 'Teacher', 'engineer'],
 'Salary': [2344, 34653, 23453, 56234]}

In [15]:
df=pd.DataFrame(data)
print(df.dtypes)

Name          object
Age            int64
Occupation    object
Salary         int64
dtype: object

In [16]:
# Create a dictionary with mixed data types
data={'Name':['Rr','Mm','Aa','Ss'],
      'Age':[25,23,24,26],
      'Occupation' :['Data Sci','Software','Teacher','engineer'],
      'Salary':['BDT 2344','BDT 34653','BDT 23453','BDT 56234']}
data

{'Name': ['Rr', 'Mm', 'Aa', 'Ss'],
 'Age': [25, 23, 24, 26],
 'Occupation': ['Data Sci', 'Software', 'Teacher', 'engineer'],
 'Salary': ['BDT 2344', 'BDT 34653', 'BDT 23453', 'BDT 56234']}

In [17]:
df=pd.DataFrame(data)
print(df.dtypes)

Name          object
Age            int64
Occupation    object
Salary        object
dtype: object

## Datetime

In [20]:
#create a list of dates 
date=['2026-04-16','2026-04-17','2026-04-18']
df1=pd.DataFrame({'Date':date})
df1['Date'].dtype

dtype('O')

In [24]:
timestamps=pd.to_datetime(date)
df2=pd.DataFrame({'Date2':timestamps})
df2['Date2'].dtype

dtype('<M8[ns]')

In [25]:
df2

       Date2
0 2026-04-16
1 2026-04-17
2 2026-04-18